// Fallback/seed data for when APIs are unavailable
export const SEED_MODELS = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerIcon: 'cloud',
    arenaElo: 1304,
    qualityScore: 98,
    inputPricePerMToken: 5.00,
    outputPricePerMToken: 15.00,
    cachedInputPrice: 2.50,
    tokensPerSecond: 82,
    latencyMs: 280,
    contextWindow: 128000,
    contextLabel: '128K',
    license: 'proprietary',
    modalities: ['text', 'vision'],
    taskStrengths: ['reasoning', 'code', 'chat', 'creative'],
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    providerIcon: 'cognition',
    arenaElo: 1288,
    qualityScore: 96,
    inputPricePerMToken: 3.00,
    outputPricePerMToken: 15.00,
    cachedInputPrice: 0.30,
    tokensPerSecond: 74,
    latencyMs: 320,
    contextWindow: 200000,
    contextLabel: '200K',
    license: 'proprietary',
    modalities: ['text', 'vision'],
    taskStrengths: ['code', 'reasoning', 'chat'],
  },
  {
    id: 'gemini-1-5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    providerIcon: 'language',
    arenaElo: 1265,
    qualityScore: 92,
    inputPricePerMToken: 3.50,
    outputPricePerMToken: 10.50,
    cachedInputPrice: 0.88,
    tokensPerSecond: 112,
    latencyMs: 250,
    contextWindow: 1000000,
    contextLabel: '1M',
    license: 'proprietary',
    modalities: ['text', 'vision', 'audio'],
    taskStrengths: ['reasoning', 'chat', 'creative'],
  },
  {
    id: 'llama-3-70b',
    name: 'Llama 3 70B',
    provider: 'Meta',
    providerIcon: 'hub',
    arenaElo: 1242,
    qualityScore: 88,
    inputPricePerMToken: 0.80,
    outputPricePerMToken: 0.80,
    cachedInputPrice: 0.40,
    tokensPerSecond: 145,
    latencyMs: 180,
    contextWindow: 8192,
    contextLabel: '8K',
    license: 'open',
    modalities: ['text'],
    taskStrengths: ['code', 'reasoning', 'chat'],
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'Mistral',
    providerIcon: 'waves',
    arenaElo: 1231,
    qualityScore: 85,
    inputPricePerMToken: 2.00,
    outputPricePerMToken: 6.00,
    cachedInputPrice: 1.00,
    tokensPerSecond: 95,
    latencyMs: 300,
    contextWindow: 32000,
    contextLabel: '32K',
    license: 'proprietary',
    modalities: ['text'],
    taskStrengths: ['reasoning', 'code', 'chat'],
  },
  {
    id: 'grok-1-5',
    name: 'Grok-1.5',
    provider: 'xAI',
    providerIcon: 'smart_toy',
    arenaElo: 1215,
    qualityScore: 82,
    inputPricePerMToken: 5.00,
    outputPricePerMToken: 15.00,
    cachedInputPrice: 2.50,
    tokensPerSecond: 68,
    latencyMs: 400,
    contextWindow: 131072,
    contextLabel: '128K',
    license: 'proprietary',
    modalities: ['text'],
    taskStrengths: ['reasoning', 'creative'],
  },
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'Cohere',
    providerIcon: 'dynamic_form',
    arenaElo: 1198,
    qualityScore: 80,
    inputPricePerMToken: 3.00,
    outputPricePerMToken: 15.00,
    cachedInputPrice: 1.50,
    tokensPerSecond: 65,
    latencyMs: 350,
    contextWindow: 128000,
    contextLabel: '128K',
    license: 'proprietary',
    modalities: ['text'],
    taskStrengths: ['chat', 'reasoning'],
  },
  {
    id: 'qwen-1-5-chat',
    name: 'Qwen 1.5 Chat',
    provider: 'Alibaba',
    providerIcon: 'translate',
    arenaElo: 1180,
    qualityScore: 78,
    inputPricePerMToken: 0.50,
    outputPricePerMToken: 1.50,
    cachedInputPrice: 0.25,
    tokensPerSecond: 140,
    latencyMs: 200,
    contextWindow: 32000,
    contextLabel: '32K',
    license: 'open',
    modalities: ['text'],
    taskStrengths: ['chat', 'code'],
  },
]
