export const PROVIDERS = [
  {
    id: 'together-ai',
    name: 'Together AI',
    icon: 'hub',
    models: 200,
    priceRange: '$0.03 - $4.00',
    speedTier: 'Fast',
    description: 'Open-source model hosting with competitive pricing',
    url: 'https://together.ai',
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: 'bolt',
    models: 25,
    priceRange: '$0.06 - $1.50',
    speedTier: 'Ultra-fast',
    description: 'LPU-powered inference with industry-leading latency',
    url: 'https://groq.com',
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    icon: 'cloud',
    models: 40,
    priceRange: '$0.25 - $15.00',
    speedTier: 'Standard',
    description: 'Enterprise-grade managed AI with AWS integration',
    url: 'https://aws.amazon.com/bedrock',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    icon: 'replay',
    models: 350,
    priceRange: '$0.05 - $3.50',
    speedTier: 'Fast',
    description: 'Run open-source models with simple API',
    url: 'https://replicate.com',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'route',
    models: 300,
    priceRange: '$0 - $60.00',
    speedTier: 'Varies',
    description: 'Unified API across 50+ providers, best price routing',
    url: 'https://openrouter.ai',
  },
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    icon: 'local_fire_department',
    models: 50,
    priceRange: '$0.10 - $3.00',
    speedTier: 'Fast',
    description: 'Optimized inference for production workloads',
    url: 'https://fireworks.ai',
  },
]

export const GPU_PRICING = [
  { gpu: 'H100 80GB', vram: '80GB', provider: 'Lambda', pricePerHour: 2.49, throughput: '~800 tok/s' },
  { gpu: 'H100 80GB', vram: '80GB', provider: 'RunPod', pricePerHour: 3.29, throughput: '~800 tok/s' },
  { gpu: 'A100 80GB', vram: '80GB', provider: 'Lambda', pricePerHour: 1.29, throughput: '~400 tok/s' },
  { gpu: 'A100 80GB', vram: '80GB', provider: 'AWS', pricePerHour: 3.06, throughput: '~400 tok/s' },
  { gpu: 'L40S 48GB', vram: '48GB', provider: 'RunPod', pricePerHour: 0.74, throughput: '~250 tok/s' },
]
