export const PROVIDERS = [
  {
    id: 'together-ai',
    name: 'Together AI',
    icon: 'hub',
    models: 200,
    priceRange: '$0.03 - $4.00',
    speedTier: 'Fast',
    description: 'Open-source model hosting with competitive pricing',
    url: 'https://together.ai',
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: 'bolt',
    models: 25,
    priceRange: '$0.06 - $1.50',
    speedTier: 'Ultra-fast',
    description: 'LPU-powered inference with industry-leading latency',
    url: 'https://groq.com',
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    icon: 'cloud',
    models: 40,
    priceRange: '$0.25 - $15.00',
    speedTier: 'Standard',
    description: 'Enterprise-grade managed AI with AWS integration',
    url: 'https://aws.amazon.com/bedrock',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    icon: 'replay',
    models: 350,
    priceRange: '$0.05 - $3.50',
    speedTier: 'Fast',
    description: 'Run open-source models with simple API',
    url: 'https://replicate.com',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'route',
    models: 300,
    priceRange: '$0 - $60.00',
    speedTier: 'Varies',
    description: 'Unified API across 50+ providers, best price routing',
    url: 'https://openrouter.ai',
  },
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    icon: 'local_fire_department',
    models: 50,
    priceRange: '$0.10 - $3.00',
    speedTier: 'Fast',
    description: 'Optimized inference for production workloads',
    url: 'https://fireworks.ai',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: 'psychology',
    models: 8,
    priceRange: '$0.25 - $15.00',
    speedTier: 'Fast',
    description: 'Claude models with industry-leading safety and reasoning',
    url: 'https://anthropic.com',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'auto_awesome',
    models: 15,
    priceRange: '$0.15 - $60.00',
    speedTier: 'Fast',
    description: 'GPT and o-series models for general and reasoning tasks',
    url: 'https://openai.com',
  },
  {
    id: 'google-vertex',
    name: 'Google Vertex AI',
    icon: 'language',
    models: 12,
    priceRange: '$0.10 - $10.00',
    speedTier: 'Fast',
    description: 'Gemini models with multimodal capabilities on GCP',
    url: 'https://cloud.google.com/vertex-ai',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    icon: 'shield',
    models: 12,
    priceRange: '$0.50 - $60.00',
    speedTier: 'Standard',
    description: 'Enterprise OpenAI deployment with Azure compliance',
    url: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: 'smart_toy',
    models: 500,
    priceRange: '$0 - $5.00',
    speedTier: 'Varies',
    description: 'Largest open-source model hub with serverless inference',
    url: 'https://huggingface.co',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    icon: 'memory',
    models: 80,
    priceRange: '$0.04 - $2.00',
    speedTier: 'Fast',
    description: 'Low-cost inference with automatic model optimization',
    url: 'https://deepinfra.com',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    icon: 'search',
    models: 5,
    priceRange: '$0.20 - $3.00',
    speedTier: 'Fast',
    description: 'Search-augmented models for real-time knowledge tasks',
    url: 'https://perplexity.ai',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: 'air',
    models: 6,
    priceRange: '$0.10 - $4.00',
    speedTier: 'Ultra-fast',
    description: 'European frontier models with efficient architectures',
    url: 'https://mistral.ai',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    icon: 'dynamic_form',
    models: 8,
    priceRange: '$0.15 - $3.00',
    speedTier: 'Fast',
    description: 'Enterprise NLP with RAG-optimized embeddings and search',
    url: 'https://cohere.com',
  },
]

export const GPU_PRICING = [
  { gpu: 'H200 141GB', vram: '141GB', vramNum: 141, provider: 'CoreWeave', pricePerHour: 4.25, throughput: '~1200 tok/s', throughputNum: 1200, tflops: 1979 },
  { gpu: 'H100 80GB', vram: '80GB', vramNum: 80, provider: 'Lambda', pricePerHour: 2.49, throughput: '~800 tok/s', throughputNum: 800, tflops: 989 },
  { gpu: 'H100 80GB', vram: '80GB', vramNum: 80, provider: 'RunPod', pricePerHour: 3.29, throughput: '~800 tok/s', throughputNum: 800, tflops: 989 },
  { gpu: 'MI300X 192GB', vram: '192GB', vramNum: 192, provider: 'Lambda', pricePerHour: 3.99, throughput: '~900 tok/s', throughputNum: 900, tflops: 1307 },
  { gpu: 'A100 80GB', vram: '80GB', vramNum: 80, provider: 'Lambda', pricePerHour: 1.29, throughput: '~400 tok/s', throughputNum: 400, tflops: 312 },
  { gpu: 'A100 80GB', vram: '80GB', vramNum: 80, provider: 'AWS', pricePerHour: 3.06, throughput: '~400 tok/s', throughputNum: 400, tflops: 312 },
  { gpu: 'L40S 48GB', vram: '48GB', vramNum: 48, provider: 'RunPod', pricePerHour: 0.74, throughput: '~250 tok/s', throughputNum: 250, tflops: 366 },
  { gpu: 'A10G 24GB', vram: '24GB', vramNum: 24, provider: 'AWS', pricePerHour: 1.00, throughput: '~150 tok/s', throughputNum: 150, tflops: 125 },
  { gpu: 'RTX 4090 24GB', vram: '24GB', vramNum: 24, provider: 'Vast.ai', pricePerHour: 0.44, throughput: '~180 tok/s', throughputNum: 180, tflops: 330 },
  { gpu: 'L4 24GB', vram: '24GB', vramNum: 24, provider: 'GCP', pricePerHour: 0.60, throughput: '~120 tok/s', throughputNum: 120, tflops: 121 },
]
